version: '3.4'

services:
    
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=12345
        ports:
            - "5432:5432"
        expose:
            - "5432"
            
    rabbit-server:
        image: rabbitmq:3.9.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=user
        ports:
            - 5672:5672
            - 15672:15672
        expose:
            - "5672"
            - "15672"